package utilities;

public enum MessageTypes {

	FIRST_MESSAGE, 
	SGH_STATE, 
	UMIDITY, UMIDITY_VALUE, UMIDITY_DATE, 
	IS_WATERING, WATERING_LIST, WATERING_DURATION, WATERING_DATE, 
	MANUALMODE, 
	WARNING,

}
